### ISSUE TITLE
Missing function zen_draw_order_status_dropdown_batch_update

### ISSUE THREAD

**Issue by torvista** [torvista/Zen_Cart-Batch_Order_Update#1]
test server 1.5.7c 7.4 php

HTML Code:
[31-Jul-2021 04:14:29 UTC] PHP Fatal error: Uncaught Error: Call to undefined function zen_draw_order_status_dropdown_batch_update() in /admin/orders.php:635
Stack trace:
#0 /admin/index.php(11): require()
#1 {main}
thrown in /admin/orders.php on line 635

[31-Jul-2021 04:14:29 UTC] Request URI: /..../index.php?cmd=orders&status=1, IP address: xxxxxxxxx
--> PHP Fatal error: Uncaught Error: Call to undefined function zen_draw_order_status_dropdown_batch_update() in /admin/orders.php:635
Stack trace:
#0 /admin/index.php(11): require()
#1 {main}
thrown in /admin/orders.php on line 635.

**Comment by torvista** [comment]
fixed in https://github.com/torvista/Zen_Cart-Batch_Order_Update/commit/8c79507ff81735b17c8d4d0f872d830e3485e7a8
